name: Deploy Dashboard

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy sqlite3
    
    - name: Generate sample data
      run: |
        python scripts/create_sample_dashboard_data.py
    
    - name: Validate data files
      run: |
        python -c "import pandas as pd; print('Data validation passed')"
    
    - name: Create deployment package
      run: |
        zip -r dashboard-package.zip data/ config/ docs/ scripts/
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dashboard-package
        path: dashboard-package.zip
